---
- name: Check if running on systemd
  stat: path=/sbin/init
  register: sbin_init
  changed_when: false
  check_mode: no

- name: Establish some role-related facts
  set_fact:
    mongodb_is_systemd: "{{ sbin_init.stat.islnk is defined and sbin_init.stat.islnk }}"

- name: Add APT key
  apt_key:
    keyserver: "{{ mongodb_apt_keyserver }}"
    id: "{{ mongodb_apt_key_id[mongodb_major_version] }}"

- name: Add APT repository
  apt_repository: repo="{{ mongodb_repository[mongodb_major_version] }}" update_cache=yes

- name: Install MongoDB package
  apt:
    name:
      - mongodb-org
      - numactl
    state: present

- name: Add systemd configuration if present
  copy: src=mongodb.service dest=/lib/systemd/system/mongodb.service owner=root group=root mode=0640
  when: mongodb_is_systemd

- name: Add symlink for systemd
  file: src=/lib/systemd/system/mongodb.service dest=/etc/systemd/system/multi-user.target.wants/mongodb.service state=link
  when: mongodb_is_systemd
  notify: reload systemd

- name: reload systemd
  shell: systemctl daemon-reload

- meta: flush_handlers

- name: Install PIP
  apt:
    pkg:
      - python-dev
      - python-pip

- name: Install PyMongo from PIP
  pip:
    name: pymongo
    state: "{{ mongodb_pymongo_pip_version is defined | ternary('present', 'latest') }}"
    version: "{{ mongodb_pymongo_pip_version | default(omit) }}"
